### Get the pokemon information
GET  http://localhost:1234/pokemon/ditto

### Create pokemon 
POST http://localhost:3000/pokemon
Content-Type: application/json

{
    "name": "dex",
    "types": "normal",
    "moves": [
        "transform"
    ]
}

### Get Pokemon

GET http://localhost:3000