### Load all movies
GET http://localhost:1234/movies

### Load a movie by id
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Load movies by genre
GET http://localhost:1234/movies?genre=scI-Fi

### Insert a movie
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Godfacther"
}